### ISSUE TITLE
9.21日 运行出错

### ISSUE THREAD

**Issue by iGuoBao** [sang8052/py_pctv#2]
[2024-09-21 20:56:49][INFO]运行路径:C:\Users\Jin\Downloads\v1.0.1.beta
{THREAD-1}[2024-09-21 20:56:49][INFO]请求直播间播放地址
[2024-09-21 20:56:49][INFO]线程[五星体育直播]启动成功
[2024-09-21 20:56:49][INFO]WSGIServer Listen 0.0.0.0:9655
{THREAD-1}[2024-09-21 20:56:49][INFO]直播流播放地址:https://cms-tvflow.gsports.net.cn/wxtv/epg001.m3u8?auth_key=1726925212-0-0-d6cc61a5c0aa960b3c009a6efa4ad8af
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "tv\tv_5xtv.py", line 51, in run
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './static/data'

**Comment by sang8052** [comment]
稍等 ，缺少前端文件



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jin ***@***.***&gt;; 
发送时间: 2024年9月21日(星期六) 晚上8:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [sang8052/py_pctv] 9.21日 运行出错 (Issue #2)














 
[2024-09-21 20:56:49][INFO]运行路径:C:\Users\Jin\Downloads\v1.0.1.beta
 {THREAD-1}[2024-09-21 20:56:49][INFO]请求直播间播放地址
 [2024-09-21 20:56:49][INFO]线程[五星体育直播]启动成功
 [2024-09-21 20:56:49][INFO]WSGIServer Listen 0.0.0.0:9655
 {THREAD-1}[2024-09-21 20:56:49][INFO]直播流播放地址:https://cms-tvflow.gsports.net.cn/wxtv/epg001.m3u8?auth_key=1726925212-0-0-d6cc61a5c0aa960b3c009a6efa4ad8af
 Exception in thread Thread-1:
 Traceback (most recent call last):
 File "threading.py", line 1016, in _bootstrap_inner
 File "tv\tv_5xtv.py", line 51, in run
 FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './static/data'

**Comment by sang8052** [comment]
[static.zip](https://github.com/user-attachments/files/17084133/static.zip)
把这个文件解压到和exe 的相同目录下. 即如图所示

![image](https://github.com/user-attachments/assets/20e9cc9c-db9c-460d-956d-9c9ff4747cb1)
